
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-002068ed284fb165b
      SecurityGroups: 
      - Ref: InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: InstanceId of the EC2 instance
    Value:
      Ref: EC2Instance
  # PublicDNS:
  #   Description: Public DNSName of the instance
  #   Value: 
  #     GetAtt:
  #     - EC2Instance
  #     - PublicDNSName
  # PublicIp:
  #   Description: Public IP address of the Ec2 instance
  #   Value: 
  #     GetAtt:
  #     - EC2Instance
  #     - PublicIp
